stages:
  - quality
  - tests

code:
  stage: quality
  script:
    - export DEBIAN_FRONTEND=noninteractive
    - apt-get update
    - apt-get dist-upgrade -y
    - apt-get install -y libperl-critic-perl make
    - perlcritic --gentle "$CI_PROJECT_DIR"

tests:
  stage: tests
  script:
    - export DEBIAN_FRONTEND=noninteractive
    - apt-get update
    - apt-get dist-upgrade -y
    - apt-get install -y git make
    - apt-get install -y mysql-server
    - cd "$CI_PROJECT_DIR"
    - ./update-git-modules
    - perl Makefile.PL
    - make test

