stages:
  - codequality
  - tests

quality:
  stage: code
  script:
    - DEBIAN_FRONTEND=noninteractive
    - apt-get update
    - apt-get dist-upgrade -y
    - apt-get install -y libperl-critic-perl
    - perlcritic --gentle "$CI_PROJECT_DIR"

tests:
  stage: tests
  script:
    - DEBIAN_FRONTEND=noninteractive
    - apt-get update
    - apt-get dist-upgrade -y
    - apt-get install -y git
    - apt-get install -y mysql-server
    - cd "$CI_PROJECT_DIR"
    - ./update-git-modules

