stages:
  - requirements
  - codequality
  - tests

publish:
  stage: requirements
  script:
    - apt-get update
    - apt-get dist-upgrade -y
    - apt-get install -y git
    - apt-get install -y libperl-critic-perl

publish:
  stage: codequality
  script:
    - perlcritic --gentle "$CI_PROJECT_DIR"

publish:
  stage: tests
  script:
    - cd "$CI_PROJECT_DIR"
    - ./update-git-modules

